"""Slicing.

Two paths. When a slicer binary is configured we run the real thing against the real machine
profile and read time and mass out of the generated toolpaths — that is what makes an instant
quote honest. Without one we fall back to a geometry estimator, and every downstream object is
flagged `estimated=True` so nothing silently presents a guess as a measurement.

Two slicer families are supported and they differ more than the shared name suggests:

  * **PrusaSlicer** takes a flat `.ini` config and exports G-code directly. Profiles are
    generated by `scripts/gen_slicer_profiles.py` from the shop and material data, so the
    density the slicer weighs filament with is the same one the quote is priced on.
  * **Bambu Studio / OrcaSlicer** take JSON settings bundles and export a `.3mf` project, which
    is what a Bambu machine actually needs — the plate layout and AMS filament assignment live
    in the 3mf, and raw G-code has nowhere to put them. See docs/decisions.md D1.
"""

from __future__ import annotations

import math
import os
import re
import shutil
import subprocess
import tempfile
import zipfile
from enum import StrEnum
from pathlib import Path
from typing import Any

from .config import repo_root, shop_config
from .materials import Material
from .schemas import GeometryReport, SliceResult

SLICER_CANDIDATES = ("prusa-slicer", "prusaslicer", "bambu-studio", "orca-slicer", "orcaslicer")
SLICE_TIMEOUT_S = 300

# Effective volumetric flow for a 0.4 mm nozzle once travel, acceleration and cooling limits are
# accounted for. Bench flow is higher; this is the number that matches real wall-clock times.
EFFECTIVE_FLOW_MM3_S = 9.0

# Per-layer fixed overhead: z-hop, seam, retraction, minimum layer time.
LAYER_OVERHEAD_S = 1.6

TIME_RE = re.compile(
    r";\s*(?:estimated printing time|total estimated time)"
    r"(?:\s*\(normal mode\))?\s*=\s*"
    r"(?:(\d+)d\s*)?(?:(\d+)h\s*)?(?:(\d+)m\s*)?(?:(\d+)s)?",
    re.IGNORECASE,
)
FILAMENT_G_RE = re.compile(r";\s*(?:total )?filament used \[g\]\s*=\s*([\d.]+)", re.IGNORECASE)
FILAMENT_CM3_RE = re.compile(r";\s*filament used \[cm3\]\s*=\s*([\d.]+)", re.IGNORECASE)
SUPPORT_G_RE = re.compile(
    r";\s*support (?:filament|material) used \[g\]\s*=\s*([\d.]+)", re.IGNORECASE
)


class SlicerFamily(StrEnum):
    PRUSA = "prusa"
    ORCA = "orca"


class SlicerUnavailable(RuntimeError):
    pass


def find_slicer() -> str | None:
    """Locate a slicer binary from SLICER_BIN or the PATH."""
    explicit = os.environ.get("SLICER_BIN")
    if explicit and Path(explicit).exists():
        return explicit
    for candidate in SLICER_CANDIDATES:
        found = shutil.which(candidate)
        if found:
            return found
    return None


def slicer_family(binary: str) -> SlicerFamily:
    name = Path(binary).name.lower()
    return SlicerFamily.PRUSA if "prusa" in name else SlicerFamily.ORCA


def profile_dir(family: SlicerFamily) -> Path:
    configured = os.environ.get("SLICER_PROFILES")
    base = Path(configured) if configured else repo_root() / "config" / "slicer-profiles"
    if not base.is_absolute():
        base = repo_root() / base
    return base / ("prusaslicer" if family is SlicerFamily.PRUSA else "orca")


def _bed_centre() -> tuple[float, float]:
    printers = [p for p in shop_config().get("printers", []) if p.get("kind") != "resin"]
    if not printers:
        return (125.0, 105.0)
    x, y, _ = max(printers, key=lambda p: p["build_volume_mm"][0])["build_volume_mm"]
    return (x / 2.0, y / 2.0)


# --------------------------------------------------------------------------------------
# Estimator fallback
# --------------------------------------------------------------------------------------


def estimate(geometry: GeometryReport, material: Material, settings: dict[str, Any]) -> SliceResult:
    """Estimate time and mass from geometry alone.

    Deliberately conservative and explainable. Shell volume is surface area times the wall
    thickness; whatever is left inside is filled at the infill fraction. Close enough to quote
    from when it is clearly labelled as an estimate and reviewed before it is committed to.
    """
    walls = int(settings.get("walls", 3))
    infill = float(settings.get("infill_percent", 20)) / 100.0
    layer_height = float(settings.get("layer_height_mm", 0.2))
    extrusion_width = 0.45

    shell_thickness = walls * extrusion_width
    shell_volume = min(geometry.surface_area_mm2 * shell_thickness, geometry.volume_mm3)
    core_volume = max(geometry.volume_mm3 - shell_volume, 0.0)
    extruded_mm3 = shell_volume + core_volume * infill

    support_mm3 = 0.0
    if geometry.overhang_fraction > 0.05:
        # Support scales with the overhanging area and how far it has to reach down. Half the
        # part height is a reasonable mean drop for a typical part.
        support_area = geometry.surface_area_mm2 * geometry.overhang_fraction
        support_mm3 = support_area * (geometry.bbox_mm[2] * 0.5) * 0.12

    density = material.density_g_cm3 / 1000.0  # g per mm^3
    filament_g = extruded_mm3 * density
    support_g = support_mm3 * density

    layers = max(1, math.ceil(geometry.bbox_mm[2] / layer_height))
    extrude_seconds = (extruded_mm3 + support_mm3) / EFFECTIVE_FLOW_MM3_S
    overhead_seconds = layers * LAYER_OVERHEAD_S
    print_minutes = (extrude_seconds + overhead_seconds) / 60.0

    return SliceResult(
        print_minutes=round(print_minutes, 1),
        # Three decimals, not two: a part small enough to round to 0.00 g would otherwise trip
        # the "we could not measure this" guard in pricing and mask the real problem, which is
        # usually that the model is scaled wrong.
        filament_g=round(filament_g, 3),
        support_g=round(support_g, 3),
        layer_height_mm=layer_height,
        estimated=True,
        slicer="estimator",
    )


# --------------------------------------------------------------------------------------
# Command construction
# --------------------------------------------------------------------------------------


def _prusa_command(
    binary: str,
    mesh_path: Path,
    material: Material,
    settings: dict[str, Any],
    output: Path,
    profiles: Path,
) -> list[str]:
    cx, cy = _bed_centre()
    cmd = [binary, "--export-gcode", "--output", str(output), "--center", f"{cx},{cy}"]

    profile = profiles / f"{material.id}.ini"
    if profile.exists():
        cmd += ["--load", str(profile)]
    else:
        # Without a profile the slicer would weigh filament at zero density, so at minimum give
        # it the numbers the quote depends on.
        cmd += [
            "--nozzle-diameter",
            "0.4",
            "--filament-diameter",
            "1.75",
            "--filament-density",
            str(material.density_g_cm3),
        ]

    # Per-job overrides come after --load so they win over the profile.
    cmd += [
        "--layer-height",
        str(settings.get("layer_height_mm", 0.2)),
        "--perimeters",
        str(settings.get("walls", 3)),
        "--fill-density",
        f"{settings.get('infill_percent', 20)}%",
    ]
    pattern = settings.get("infill_pattern")
    if pattern:
        cmd += ["--fill-pattern", str(pattern)]

    cmd.append(str(mesh_path))
    return cmd


def _orca_command(
    binary: str,
    mesh_path: Path,
    material: Material,
    settings: dict[str, Any],
    output: Path,
    profiles: Path,
) -> list[str]:
    cmd = [
        binary,
        "--export-3mf",
        str(output),
        "--slice",
        "0",
        "--layer-height",
        str(settings.get("layer_height_mm", 0.2)),
        "--wall-loops",
        str(settings.get("walls", 3)),
        "--sparse-infill-density",
        f"{settings.get('infill_percent', 20)}%",
    ]
    machine = profiles / "machine.json"
    process = profiles / f"{material.id}.json"
    if machine.exists() and process.exists():
        cmd += ["--load-settings", f"{machine};{process}"]
    cmd.append(str(mesh_path))
    return cmd


def _build_command(
    binary: str,
    mesh_path: Path,
    material: Material,
    settings: dict[str, Any],
    output: Path,
) -> list[str]:
    family = slicer_family(binary)
    profiles = profile_dir(family)
    builder = _prusa_command if family is SlicerFamily.PRUSA else _orca_command
    return builder(binary, mesh_path, material, settings, output, profiles)


def artifact_suffix(binary: str | None = None) -> str:
    """What the printer is actually handed: a Bambu wants a 3mf project, a Prusa takes G-code."""
    binary = binary or find_slicer() or ""
    return ".gcode" if slicer_family(binary) is SlicerFamily.PRUSA else ".3mf"


# --------------------------------------------------------------------------------------
# Reading the results back
# --------------------------------------------------------------------------------------


def _parse_gcode_stats(text: str, material: Material) -> tuple[float | None, float | None, float]:
    minutes: float | None = None
    match = TIME_RE.search(text)
    if match:
        days, hours, mins, secs = (int(g or 0) for g in match.groups())
        minutes = days * 1440 + hours * 60 + mins + secs / 60.0

    grams: float | None = None
    grams_match = FILAMENT_G_RE.search(text)
    if grams_match:
        grams = float(grams_match.group(1))

    if not grams:
        # A profile missing filament_density reports 0 g. The extruded volume is still correct
        # and it is the number only the slicer can produce, so weigh it with our own density
        # rather than throwing the slice away.
        volume_match = FILAMENT_CM3_RE.search(text)
        if volume_match:
            grams = float(volume_match.group(1)) * material.density_g_cm3

    support = 0.0
    support_match = SUPPORT_G_RE.search(text)
    if support_match:
        support = float(support_match.group(1))

    return minutes, grams, support


def _read_output_stats(
    output: Path, material: Material
) -> tuple[float | None, float | None, float]:
    """Pull stats from a .gcode file, or from the G-code embedded in a .3mf archive."""
    if output.suffix.lower() == ".3mf":
        with zipfile.ZipFile(output) as archive:
            for name in archive.namelist():
                if name.endswith(".gcode"):
                    with archive.open(name) as fh:
                        return _parse_gcode_stats(fh.read().decode("utf-8", "ignore"), material)
        return None, None, 0.0
    return _parse_gcode_stats(output.read_text(encoding="utf-8", errors="ignore"), material)


# --------------------------------------------------------------------------------------
# Public entry points
# --------------------------------------------------------------------------------------


def slice_mesh(
    mesh_path: str | Path,
    material: Material,
    settings: dict[str, Any],
    geometry: GeometryReport,
) -> SliceResult:
    """Slice for real if a slicer is available, otherwise estimate.

    Never raises on slicer failure: a quote that arrives as an estimate beats a 500.
    """
    binary = find_slicer()
    if binary is None:
        return estimate(geometry, material, settings)

    with tempfile.TemporaryDirectory() as tmp:
        output = Path(tmp) / f"quote{artifact_suffix(binary)}"
        cmd = _build_command(binary, Path(mesh_path), material, settings, output)
        try:
            subprocess.run(cmd, check=True, capture_output=True, timeout=SLICE_TIMEOUT_S, text=True)
            minutes, grams, support = _read_output_stats(output, material)
        except (subprocess.SubprocessError, OSError, zipfile.BadZipFile):
            return estimate(geometry, material, settings)

    if minutes is None or not grams:
        return estimate(geometry, material, settings)

    return SliceResult(
        print_minutes=round(minutes, 1),
        filament_g=round(grams, 3),
        # A real slice folds support into the filament total, so reporting it again here would
        # double-count it in pricing.
        support_g=round(support, 3),
        layer_height_mm=float(settings.get("layer_height_mm", 0.2)),
        estimated=False,
        slicer=Path(binary).name,
    )


def produce_artifact(
    mesh_path: str | Path,
    material: Material,
    settings: dict[str, Any],
    destination: Path,
) -> SliceResult:
    """Slice to a real file on disk, for an approved job.

    Unlike `slice_mesh`, this raises rather than estimating: an approved job needs a file the
    printer can actually run, and quietly handing back an estimate would be worse than an error.
    """
    binary = find_slicer()
    if binary is None:
        raise SlicerUnavailable(
            "No slicer binary configured. Set SLICER_BIN to your PrusaSlicer, Bambu Studio or "
            "OrcaSlicer executable, or export the plate from the slicer by hand."
        )

    destination.parent.mkdir(parents=True, exist_ok=True)
    cmd = _build_command(binary, Path(mesh_path), material, settings, destination)
    try:
        subprocess.run(cmd, check=True, capture_output=True, timeout=SLICE_TIMEOUT_S, text=True)
    except subprocess.CalledProcessError as exc:
        raise SlicerUnavailable(f"The slicer failed: {exc.stderr or exc.stdout}".strip()) from exc
    except (subprocess.SubprocessError, OSError) as exc:
        raise SlicerUnavailable(f"The slicer could not be run: {exc}") from exc

    if not destination.exists():
        raise SlicerUnavailable("The slicer produced no output file.")

    minutes, grams, support = _read_output_stats(destination, material)
    return SliceResult(
        print_minutes=round(minutes or 0.0, 1),
        filament_g=round(grams or 0.0, 3),
        support_g=round(support, 3),
        layer_height_mm=float(settings.get("layer_height_mm", 0.2)),
        estimated=False,
        slicer=Path(binary).name,
    )
