#!/usr/bin/env python3
"""Generate PrusaSlicer configuration files from the shop's own data.

The alternative — hand-maintained .ini files — drifts. If the material table says PETG is
1.27 g/cm3 and the slicer profile says 1.24, every quote is quietly wrong and nothing tells
you. Generating the profiles means the printer geometry comes from config/shop.yaml and the
filament properties come from data/materials.yaml, with one source of truth for each.

Regenerate after editing either file:

    scripts/gen_slicer_profiles.py

Output: config/slicer-profiles/prusaslicer/<material_id>.ini
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "services" / "worker" / "src"))

from worker.config import materials_config, shop_config  # noqa: E402

OUT = ROOT / "config" / "slicer-profiles" / "prusaslicer"

# PrusaSlicer names a few things differently from the material table.
FILAMENT_TYPE = {
    "pla": "PLA", "pla_tough": "PLA", "petg": "PETG", "asa": "ASA", "abs": "ABS",
    "pc": "PC", "pa6_cf": "NYLON", "pa12": "NYLON", "pp": "PP", "tpu_95a": "FLEX",
}

HEADER = """# Generated by scripts/gen_slicer_profiles.py — do not edit by hand.
# Printer geometry from config/shop.yaml; filament properties from data/materials.yaml.
# Material: {name} ({material_id})
"""

# Machine kinematics, by printer family. These matter more than anything else for the quoted
# print time: PrusaSlicer's own defaults describe an MK3-class machine at 60 mm/s, and pricing
# a CoreXY job on those numbers overcharges for time by a factor of three or four.
#
# Values track Bambu Studio's 0.20 mm Standard profile for the X1C. On a fast machine the real
# limiter is not these speeds but the hotend's melt rate — see max_volumetric_mm3_s per material.
MACHINE_PROFILES = {
    "bambu": {
        "perimeter_speed": 300,
        "external_perimeter_speed": 200,
        "infill_speed": 270,
        "solid_infill_speed": 250,
        "top_solid_infill_speed": 200,
        "support_material_speed": 150,
        "bridge_speed": 50,
        "gap_fill_speed": 150,
        "travel_speed": 500,
        "first_layer_speed": 50,
        "max_print_speed": 300,
        "default_acceleration": 10000,
        "perimeter_acceleration": 5000,
        "first_layer_acceleration": 500,
        "travel_acceleration": 10000,
        "machine_max_acceleration_extruding": "10000,10000",
        "machine_max_acceleration_travel": "10000,10000",
        "machine_max_feedrate_x": "500,500",
        "machine_max_feedrate_y": "500,500",
    },
    "prusa": {
        "perimeter_speed": 60,
        "external_perimeter_speed": 40,
        "infill_speed": 100,
        "solid_infill_speed": 80,
        "top_solid_infill_speed": 50,
        "support_material_speed": 60,
        "bridge_speed": 30,
        "gap_fill_speed": 60,
        "travel_speed": 180,
        "first_layer_speed": 25,
        "max_print_speed": 120,
        "default_acceleration": 2500,
        "perimeter_acceleration": 1500,
        "first_layer_acceleration": 500,
        "travel_acceleration": 2500,
        "machine_max_acceleration_extruding": "2500,2500",
        "machine_max_acceleration_travel": "2500,2500",
        "machine_max_feedrate_x": "200,200",
        "machine_max_feedrate_y": "200,200",
    },
}


def largest_fdm_printer() -> dict:
    printers = [p for p in shop_config().get("printers", []) if p.get("kind") != "resin"]
    if not printers:
        raise SystemExit("No FDM printer configured in config/shop.yaml")
    return max(printers, key=lambda p: (lambda v: v[0] * v[1] * v[2])(p["build_volume_mm"]))


def profile_for(material: dict, printer: dict) -> str:
    x, y, z = printer["build_volume_mm"]
    nozzle = printer.get("nozzle_mm", 0.4)
    nozzle_c = material["nozzle_c"]
    bed_c = material["bed_c"]
    kinematics_name = printer.get("kind", "prusa")
    kinematics = MACHINE_PROFILES.get(kinematics_name, MACHINE_PROFILES["prusa"])

    # A first layer that sticks is worth more than a fast one, on every material.
    first_layer_c = nozzle_c + 5
    first_bed_c = bed_c + (5 if bed_c < 100 else 0)

    lines = [
        HEADER.format(name=material["name"], material_id=material["id"]),
        "# --- printer ---",
        "printer_technology = FFF",
        "gcode_flavor = marlin2",
        f"nozzle_diameter = {nozzle}",
        f"bed_shape = 0x0,{x}x0,{x}x{y},0x{y}",
        f"max_print_height = {z}",
        "retract_length = 0.8",
        "retract_speed = 35",
        "",
        f"# --- kinematics ({kinematics_name}) ---",
        *[f"{key} = {value}" for key, value in kinematics.items()],
        "",
        "# --- filament ---",
        "filament_diameter = 1.75",
        # The density the quote is priced on is the one in the material table, and the slicer
        # must use the same number or the mass it reports will not match the price.
        f"filament_density = {material['density_g_cm3']}",
        f"filament_cost = {material['cost_per_kg']}",
        f"filament_type = {FILAMENT_TYPE.get(material['id'], 'PLA')}",
        # On a fast machine this is the real speed limit, not the feedrates above.
        f"filament_max_volumetric_speed = {material['max_volumetric_mm3_s']}",
        f"temperature = {nozzle_c}",
        f"first_layer_temperature = {first_layer_c}",
        f"bed_temperature = {bed_c}",
        f"first_layer_bed_temperature = {first_bed_c}",
        "",
        "# --- print ---",
        "layer_height = 0.2",
        "first_layer_height = 0.25",
        "perimeters = 3",
        "fill_density = 20%",
        "fill_pattern = gyroid",
        "top_solid_layers = 4",
        "bottom_solid_layers = 3",
        "skirts = 1",
        # Let the slicer decide where support is needed rather than guessing from the mesh.
        "support_material = 1",
        "support_material_auto = 1",
        "support_material_threshold = 45",
        "support_material_buildplate_only = 0",
    ]

    if material["warp"] == "high":
        # High-warp materials lift at the corners without a brim, and a failed print costs far
        # more than the few grams a brim adds.
        lines += ["brim_width = 5", "brim_type = outer_only"]
    else:
        lines += ["brim_width = 0"]

    if material["id"] == "tpu_95a":
        # Flexible filament buckles if pushed hard; slow it down and retract barely at all.
        lines += [
            "perimeter_speed = 20",
            "infill_speed = 25",
            "retract_length = 0.4",
        ]

    return "\n".join(lines) + "\n"


def main() -> None:
    printer = largest_fdm_printer()
    OUT.mkdir(parents=True, exist_ok=True)

    written = []
    for material in materials_config()["materials"]:
        if material["process"] != "fdm" or material.get("nozzle_c") is None:
            continue
        target = OUT / f"{material['id']}.ini"
        target.write_text(profile_for(material, printer))
        written.append(target.name)

    print(f"Printer: {printer['name']} {printer['build_volume_mm']} mm, "
          f"{printer.get('nozzle_mm', 0.4)} mm nozzle")
    print(f"Wrote {len(written)} profiles to {OUT.relative_to(ROOT)}:")
    for name in written:
        print(f"  {name}")


if __name__ == "__main__":
    main()
